### ISSUE TITLE
Error When Opening Tagbar

### ISSUE THREAD

**Issue by Fader1997** [jyzeng17/quick-neovim-setup#4]
OS Version: Ubuntu 16.04 desktop

Tagbar: Exuberant ctags not found!                                                                                                                                                                          
Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.

There is an little error!

**Comment by BroLeaf** [comment]
I think that would not be an error.
Why not try to install `Exuberant ctags` fist?

There are some hints when you create an issue or discuss with others:
- You should tell others what command you use 
- Use "```  ```" to separate message and your script
- When you can not install correctly, you need to post your version of vim and nvim. And find what exactly cause error, not just post some message and say that is error.
